WITH TEMP AS (
    SELECT T.ITEM_ID
    FROM ITEM_INFO AS I JOIN ITEM_TREE AS T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE RARITY = 'RARE'
)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I JOIN TEMP AS T
ON I.ITEM_ID = T.ITEM_ID
ORDER BY I.ITEM_ID DESC