WITH TEMP AS (
    SELECT WRITER_ID, COUNT(*) AS `COUNT`
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT U.USER_ID, U.NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS `전체주소`, 
CONCAT(LEFT(TLNO, 3), "-", MID(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) AS `전화번호`
FROM TEMP AS T JOIN USED_GOODS_USER AS U
ON U.USER_ID = T.WRITER_ID
ORDER BY U.USER_ID DESC

